name: CI Pipeline - Build and Test

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  JAVA_VERSION: '17'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven Cache Key
        id: set-cache-key 
        run: |
          # Define a variável MAVEN_CACHE_KEY aqui, onde 'runner.os' é válido
          echo "MAVEN_CACHE_KEY=${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}" >> $GITHUB_ENV

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ env.MAVEN_CACHE_KEY }} 
          restore-keys: |
            ${{ env.MAVEN_CACHE_KEY }}
            ${{ runner.os }}-maven-

      - name: Build and Run Tests (Maven)
        run: |
          cd backend
          mvn clean install -DskipTests sonar:sonar \
            -Dsonar.projectKey=wefit_cadastro_service \
            -Dsonar.organization=your-sonarcloud-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.tests=src/test/java \
            -Dsonar.test.inclusions=**/*Test.java \
            -Dsonar.test.exclusions=**/*IntegrationTest.java \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.surefire.reportPaths=target/surefire-reports \
            -Dsonar.junit.reportPaths=target/surefire-reports

      - name: Run Integration Tests (Maven)
        run: |
          cd backend
          mvn test -Pintegration-tests

      - name: Publish Test Results (Surefire Reports)
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/target/surefire-reports/

      - name: Publish JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: backend/target/site/jacoco/

      - name: Setup Node.js for Semantic Release
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Semantic Release CLI
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec

      - name: Run Semantic Release
        run: |
          cd backend
          semantic-release \
            --branches main \
            --plugins "@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/changelog,@semantic-release/npm,@semantic-release/git,@semantic-release/github,@semantic-release/exec" \
            --exec "mvn -B release:prepare release:perform -DskipTests -Darguments.skipTests=true -DdryRun=\${dryRun} -DreleaseVersion=\${nextRelease.version} -DdevelopmentVersion=\${nextRelease.version}-SNAPSHOT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
