name: CI Pipeline - Build and Test

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  JAVA_VERSION: '17'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven Cache Key
        id: set-cache-key
        run: |
          echo "MAVEN_CACHE_KEY=${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}" >> $GITHUB_ENV

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ env.MAVEN_CACHE_KEY }}
          restore-keys: |
            ${{ env.MAVEN_CACHE_KEY }}
            ${{ runner.os }}-maven-

      - name: Build and Run Unit Tests
        run: |
          cd backend
          mvn clean install -Dskip.integration.tests=true

      - name: Run SonarCloud Analysis
        run: |
          cd backend
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar \
            -Dsonar.projectKey=Sobral-Dev_projeto-WeFit \
            -Dsonar.organization=sobral-dev \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.tests=src/test/java \
            -Dsonar.test.inclusions="**/*Test.java,!**/*IntegrationTest.java"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Integration Tests
        run: |
          cd backend
          mvn verify -Pintegration-tests

      - name: Publish Unit Test Results (Surefire Reports)
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/target/surefire-reports/

      - name: Publish Integration Test Results (Failsafe Reports)
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: backend/target/failsafe-reports/

      - name: Publish JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: backend/target/site/jacoco/

      - name: Setup Node.js for Semantic Release
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Semantic Release CLI
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec

      - name: Run Semantic Release
        run: |
          cd backend
          semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
